### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by cjessett** [yarino/capstone-project-2-expresso#4]
(Meets Expectations) Overall, nice work.

Remember that `import` looks for files named `index.js` in the directory given. Also, remember that you can just call `Promise.resolve` and to always prefer object shorthand.

Otherwise, your code is clean and easy to follow, nice job.

**Comment by yarino** [comment]
Thanks for your feedback cjessett.
All your issues are on Expresso.js file which came by default with the program from CodeAcademy.
